import Footer from "@/components/Footer/Footer";
import NavigationbarDesktop from "@/components/NavigationBar/NavigationbarDesktop/NavigationbarDesktop";
import ContextIndex from "@/contexts/width";

export const metadata = {
  title: "Nhà Của Mèo",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ContextIndex>
          <NavigationbarDesktop />
          {children}
        </ContextIndex>

        <Footer />
      </body>
    </html>
  );
}
